### ISSUE TITLE
Cannot install the tool

### ISSUE THREAD

**Issue by vabzter** [eskiyerli/revEDAsetup#1]
Hi revEda, I followed your installation guide and hit an issue with the docker-compose up step. Here is the log from the Visual Studio:
> Executing task: docker-compose -f "docker-compose.yml" up -d --build <

Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request      
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[904] Failed to execute script docker-compose
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker-compose -f "docker-compose.yml" up -d --build" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

I am using a Win 10 desktop with 8gB RAM and 100gB HDD.

Do let me know if I am missing something.

Thanks and regards,
vab

**Comment by eskiyerli** [comment]
Hello @vabzter, have you enabled WSL in Windows assuming that you are using Windows?
Please also have a look at the following website:
https://file-translate.com/en/blog/docker-can-not-start-on-windows

### Solution

You can fix this problem by executing the following command.
`
 "C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon`

This error is caused by the sudden shutdown of the Docker daemon, which is still alive. For this reason, switch the daemon with the above command.

If you can not find your images or volumes, please restart the Docker itself.

You may be surprised to see this error suddenly.

**Comment by eskiyerli** [comment]
Did you manage to get it working?

**Comment by vabzter** [comment]
Hello yes the  Windows Subsystem for Linux is enabled. The other issue was that the virtualization was disabled in Bios. So I enabled it. 
I think there is some issue with the docker installation. I could do the docker-compose up step successfully. 
But then the revEda tool window was not displayed.

I will try to debug it this evening.

Thanks
vab

**Comment by eskiyerli** [comment]
Have you disabled the access control in Vcxsrv?

**Comment by vabzter** [comment]
Hi got the tool open.

Yes the access control in Vcxrv was disabled and saved in the config

![image](https://user-images.githubusercontent.com/77781274/143069978-44ce2aaa-8703-40f5-bdc2-a173098ccb8a.png)

Will now explore the tool.

Thanks for your help. Please clode this ticket.
Thanks 
vab
